collections:
  authors:
    output: true
  posts:
    output: true
    permalink: ./:year/:month/:date/:title

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
